[package]
name = "kilo-rs"
version = "0.1.0"
authors = ["Jared Beller <jbellerb@vt.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termios = "0.3.1"
