[package]
name = "kilo-rs"
version = "0.1.0"
authors = ["Jared Beller <jbellerb@vt.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mio = "0.6.19"
termios = "0.3.1"
term_size = "0.3.1"
unic-segment = "0.9.0"
