[package]
name = "torrent-client"
version = "0.1.0"
authors = ["Jared Beller <jbellerb@vt.edu>"]
edition = "2018"

[dependencies]
rust-crypto = "^0.2"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
serde_bencode = "0.2"
nom = "5.1"
reqwest = "0.10"
tokio = { version = "0.2", features = ["full"] }
anyhow = "1.0"
bytes = "0.5"
tokio-util = { version = "0.3", features = ["codec"] }
num-traits = "0.2"
num-derive = "0.3"
