[package]
name = "torrent-client"
version = "0.1.0"
authors = ["Jared Beller <jbellerb@vt.edu>"]
edition = "2018"

[dependencies]
rand = "0.7"
anyhow = "1.0"
bytes = "0.5"
rust-crypto = "0.2"
tracing = "0.1"
tracing-futures = "0.2"
tracing-subscriber = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
serde_bencode = "0.2"
nom = "5.1"
tokio = { version = "0.2.22", features = ["full"] }
tokio-util = { version = "0.3", features = ["codec"] }
futures = "0.3"
reqwest = "0.10"
crossbeam-queue = "0.2"
crossbeam-utils = "0.7"
