[package]
name = "n64scale"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
image = { version = "0.24", default-features = false, features = ["png"] }
